/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package builder.design.pattern;

import builder.design.pattern.Snadwich.Sandwich;
import builder.design.pattern.Snadwich.SandwichBuilder;

public class App {


    public static void main(String[] args) {

        Sandwich sandwich = new SandwichBuilder("Baguette", "Steak")
                                .setChesse(true)
                                .setVegetables(true)
                                .setSauces(true)
                                .build();
        System.out.println("Sandwich created with bread: " + sandwich.getBread() +
        ", meat: " + sandwich.getMeat() +
        ", cheese: " + sandwich.getChesse() +
        ", vegetables: " + sandwich.getVegetables() +
        ", sauces: " + sandwich.getSauces());
        
    }
}
